### ISSUE TITLE
Error "the access token is not valid"

### ISSUE THREAD

**Issue by LauraApetroaeiJcrew** [MohammedRaji/react-ig-feed#7]
This worked amazingly fine until a few days ago, when my client pointed out that instead of the feed he sees the message "the access token is not valid".

Did Instagram change anything in their API or something that could cause this? Can someone help, please? I would appreciate it. 

PS: visit https://mohammedraji.github.io/react-ig-feed/ and in the Demo section you can see the same error message instead of the demo.
<img width="1672" alt="Screenshot 2022-01-17 at 15 18 45" src="https://user-images.githubusercontent.com/66671151/149776644-2320e126-82a9-4f88-b10b-077834459941.png">

UPDATE: Just now I generated a new token, updated it in my app and the feed is working as it should. I missed the 60 days limit, my bad.

**Comment by jeffceriello** [comment]
Hi, how have you resolved the 60 days limit?

**Comment by MohammedRaji** [comment]
> Hi, how have you resolved the 60 days limit?

please visit [facebook developers site](https://developers.facebook.com/docs/instagram-basic-display-api/guides/long-lived-access-tokens/) for more information

**Comment by jeffceriello** [comment]
Hi thank you for your reply. I'm sorry but I'm not sure what to do there. How can I refresh the access token with the react-ig-feed module?
